#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e
cd "$(dirname "$0")/.."


echo "===> Build started at…"
date "+%H:%M:%S"

# setup environment
APP_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export APP_ROOT
export APP_ENV="test"
export RACK_ROOT="$APP_ROOT"
export RACK_ENV="$APP_ENV"

test -d "/usr/share/rbenv/shims" && {
  export PATH=/usr/share/rbenv/shims:$PATH
}
export RBENV_VERSION=$(cat .ruby-version)

export PATH="$RACK_ROOT/bin:$PATH"

./script/test
